print("Nuqtalarning koordinatalarini kiriting(A(x) - x o'qidagi koordinatasi, A(y) - y o'qidagi koordinatasi)")
a1 = float(input("A(x) = "))
a2 = float(input("A(y) = "))
b1 = float(input("B(x) = "))
b2 = float(input("B(y) = "))
c1 = float(input("C(x) = "))
c2 = float(input("C(y) = "))
AB = float(((a1 - b1)**2 + (a2 - b2)**2)**(1/2))
print("AB = ", AB)
BC = float(((c1 - b1)**2 + (c2 - b2)**2)**(1/2))
print("BC = ", BC)
AC = float(((a1 - c1)**2 + (a2 - c2)**2)**(1/2))
print("AC = ", AC)
print("AB + BC = ", AB + BC)
print("AC + BC = ", AC + BC)
print("AB + AC = ", AB + AC)
print("ABxBC = ", AB * BC)
print("BCxAC = ", BC * AC)
print("ACxAB = ", AC * AB)
print("AB,BC,AC kesmalardan uchburchak yasash mumkin bo'lsa, u holda S(ABC) = ", (((AB + BC - AC)*(AB - BC + AC)*(AB + BC + AC)*(BC + AC - AB))/4)**(1/2))