print("A(x) - A sonining x inchi darajasi degan manoni anglatadi" )
A =float(input("A = "))
print("A(2) = ", A**2)
print("A(3) = ", A**3)
print("A(4) = ", A**4)
print("A(5) = ", A**5)
print("A(8) = ", A**8)
print("A(10) = ", A**10)
print("A(15) = ", A**15)
