A1 =float(input("A1 = "))
A2 =float(input("A2 = "))
B1 =float(input("B1 = "))
B2 =float(input("B2 = "))
C1 =float(input("C1 = "))
C2 =float(input("C2 = "))
D = (A1*B2 - A2*B1)
print("x = ", (C1*B2 - C2*B1)/D)
print("x = ", (A2*C2 - A2*C1)/D)
